# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemeditor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.CharField(choices=[('Algebra', 'Algebra'), ('Combinatorics', 'Combinatorics'), ('Geometry', 'Geometry'), ('Number Theory', 'Number Theory'), ('Games', 'Games'), ('Other', 'Other')], default='Algebra', max_length=20),
        ),
    ]
