# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemeditor', '0002_auto_20170402_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
