# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemeditor', '0003_auto_20170402_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='problem_status',
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_status',
            field=models.CharField(default='PN', max_length=2),
        ),
    ]
