# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemeditor', '0004_auto_20170402_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='top_solution_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='top_index',
            field=models.IntegerField(default=1),
        ),
    ]
