# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemeditor', '0005_auto_20170402_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='topic',
            field=models.CharField(choices=[('Algebra', 'Algebra'), ('Combinatorics', 'Combinatorics'), ('Games', 'Games'), ('Geometry', 'Geometry'), ('Number Theory', 'Number Theory'), ('Other', 'Other')], default='Algebra', max_length=20),
        ),
        migrations.AlterField(
            model_name='problemstatus',
            name='status',
            field=models.CharField(choices=[('PN', 'Propose for Current Year'), ('PL', 'Propose for Future Year'), ('MI', 'Needs Minor Revision'), ('MJ', 'Needs Major Revision'), ('TR', 'Trash')], default='PN', max_length=2),
        ),
    ]
