# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemeditor', '0006_auto_20170408_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('problems', models.ManyToManyField(blank=True, to='problemeditor.Problem')),
            ],
        ),
    ]
