# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problemeditor', '0008_solution_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
