# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problemeditor', '0009_solution_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=1)),
                ('problem_text', models.TextField(blank=True)),
                ('problem_latex', models.TextField(blank=True)),
                ('top_solution_number', models.IntegerField(default=0)),
                ('version_number', models.IntegerField(default=0)),
                ('author_name', models.CharField(blank=True, max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('solutions', models.ManyToManyField(blank=True, to='problemeditor.Solution')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='top_version_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_status',
            field=models.CharField(default='NP', max_length=2),
        ),
        migrations.AlterField(
            model_name='problemstatus',
            name='status',
            field=models.CharField(choices=[('NP', 'New Problem'), ('PN', 'Propose for Current Year'), ('PL', 'Propose for Future Year'), ('MI', 'Has Potential'), ('MJ', 'Needs Major Revision'), ('TR', 'Trash')], default='PN', max_length=2),
        ),
        migrations.AddField(
            model_name='problem',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_version', to='problemeditor.ProblemVersion'),
        ),
        migrations.AddField(
            model_name='problem',
            name='versions',
            field=models.ManyToManyField(blank=True, related_name='problem_version', to='problemeditor.ProblemVersion'),
        ),
    ]
