# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemeditor', '0010_auto_20170707_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemversion',
            name='label',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
