# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-01 22:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemeditor', '0012_problemversion_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemversion',
            name='authors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
