# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-03 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemeditor', '0013_auto_20170901_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemversion',
            name='deleted_solutions',
            field=models.ManyToManyField(blank=True, related_name='deleted_solutions', to='problemeditor.Solution'),
        ),
    ]
