# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-26 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemeditor', '0014_problemversion_deleted_solutions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('problems', models.ManyToManyField(blank=True, to='problemeditor.Problem')),
            ],
        ),
    ]
