# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-26 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemeditor', '0015_shortlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
