# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-26 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problemeditor', '0016_shortlist_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
