# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-26 07:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problemeditor', '0017_shortlist_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
