# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-02-01 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemeditor', '0019_auto_20190131_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='top_index',
        ),
    ]
