# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-02-01 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problemeditor', '0020_remove_topic_top_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=20)),
                ('short_topic', models.CharField(blank=True, max_length=2)),
                ('status', models.CharField(blank=True, max_length=2)),
                ('status_description', models.CharField(blank=True, max_length=30)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='status_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='problemeditor.StatusTopic'),
        ),
    ]
